### ISSUE TITLE
Convert the code 

### ISSUE THREAD

**Issue by ghost** [noarche/dorkGen#1]
Can you please convert this code into normal py script which is not like with a gui

**Comment by noarche** [comment]
Sorry for the super late response. I did not see this request until now. 
If you still need I will create a script version, I had no plans to originally.  

What makes you want it in script mode?
I can think of a few ways to improve the functionality of the GUI such as make the information entered persistent when opening closing the app. 

For convenience I have also added a .exe version.   The exe gets flagged in virustotal but it is a false positive. To be sure you can build the exe using pyinstaller from the .py file.
